export type EmployeePosition =
  | 'OVERLORD'
  | 'COMPANY_ADMIN'
  | 'HR_MANAGER'
  | 'DISPATCHER'
  | 'DRIVER'
  | 'WAREHOUSE_MANAGER'
  | 'WORKER';

export type UserStatus = 'ACTIVE' | 'INACTIVE' | 'BLOCKED';

export type EmployeeLocationFields = {
  phoneCode: string | null;
  phoneNumber: string;
  address: string | null;
  cityId: number | null;
  cityName: string | null;
  city: string | null;
  postalCode: string | null;
  timezoneId?: number | null;
  timezoneName?: string | null;
  timezoneDisplayName?: string | null;
  timezone?: string | null;
  countryId: number | null;
  countryCode: string | null;
  countryName: string | null;
  primaryWarehouseId: number | null;
  primaryWarehouseName: string | null;
};

export type EmployeeResponse = EmployeeLocationFields & {
  id: number;
  firstName: string;
  lastName: string;
  jmbg: string;
  email: string;
  autoGeneratedEmail?: boolean;
  emailManuallyOverridden?: boolean;
  emailGenerationSource?: string | null;
  suggestedGeneratedEmail?: string | null;
  generatedEmailOutdated?: boolean;
  position: EmployeePosition;
  employmentDate: string;
  salary: number;
  active: boolean;
  userId: number | null;
  companyId: number;
  companyName: string | null;
};

export type EmployeeCreateWithUserRequest = {
  firstName: string;
  lastName: string;
  jmbg: string;
  phoneCode?: string | null;
  phoneNumber: string;
  email: string;
  address?: string | null;
  cityId?: number | null;
  city?: string | null;
  postalCode?: string | null;
  timezoneId?: number | null;
  timezoneName?: string | null;
  timezoneDisplayName?: string | null;
  timezone?: string | null;
  countryId?: number | null;
  primaryWarehouseId?: number | null;
  position: EmployeePosition;
  employmentDate: string;
  salary: number;
  password: string;
  roleId: number;
  status: UserStatus;
  companyId?: number;
};

export type EmployeeUpdateRequest = {
  firstName: string;
  lastName: string;
  jmbg: string;
  phoneCode?: string | null;
  phoneNumber: string;
  email: string;
  address?: string | null;
  cityId?: number | null;
  city?: string | null;
  postalCode?: string | null;
  timezoneId?: number | null;
  timezoneName?: string | null;
  timezoneDisplayName?: string | null;
  timezone?: string | null;
  countryId?: number | null;
  primaryWarehouseId?: number | null;
  position: EmployeePosition;
  employmentDate: string;
  salary: number;
  userId?: number;
  applyGeneratedEmailSuggestion?: boolean;
};

export type EmployeeFiltersState = {
  search: string;
  position: EmployeePosition | 'ALL';
  active: 'ALL' | 'ACTIVE' | 'INACTIVE';
  linkedUser: 'ALL' | 'LINKED' | 'UNLINKED';
};

export type EmployeeListFilters = {
  search?: string;
  position?: EmployeePosition;
  active?: boolean;
  linkedUser?: 'LINKED' | 'UNLINKED';
  availableFrom?: string;
  availableTo?: string;
};

export type EmployeeUserOption = {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  enabled: boolean;
  status: UserStatus;
  roleId: number;
  roleName: string;
  employeeActive: boolean;
};

export type EmployeeRoleOption = {
  id: number;
  name: string;
  description: string | null;
};

export type EmployeeTaskResponse = {
  id: number;
  title: string;
  description: string | null;
  dueDate: string;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
  status: 'NEW' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
  assignedEmployeeId: number;
  transportOrderId: number | null;
};

export type EmployeeShiftResponse = {
  id: number;
  startTime: string;
  endTime: string;
  status: 'PLANNED' | 'ACTIVE' | 'FINISHED' | 'CANCELLED';
  notes: string;
  employeeId: number;
};

export type EmployeeFormValues = {
  firstName: string;
  lastName: string;
  jmbg: string;
  phoneCode?: string | null;
  phoneNumber: string;
  email: string;
  address?: string | null;
  cityId?: number | null;
  city?: string | null;
  postalCode?: string | null;
  timezoneId?: number | null;
  countryId?: number | null;
  primaryWarehouseId?: number | null;
  position: EmployeePosition;
  employmentDate: string;
  salary: string;
  password: string;
  status: UserStatus;
  enabled: boolean;
  companyId: string;
  applyGeneratedEmailSuggestion: boolean;
};
