import { ROLES, type Role } from '../constants/roles';

export const MODULE_ROLE_MATRIX: Record<string, readonly Role[]> = {
  dashboard: [
    ROLES.OVERLORD,
    ROLES.COMPANY_ADMIN,
    ROLES.HR_MANAGER,
    ROLES.WAREHOUSE_MANAGER,
    ROLES.DISPATCHER,
    ROLES.DRIVER,
    ROLES.WORKER,
  ],
  companies: [ROLES.OVERLORD],
  companyRequests: [ROLES.OVERLORD],
  employees: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.HR_MANAGER],
  employeeWarehouseAssignments: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.HR_MANAGER, ROLES.WAREHOUSE_MANAGER],
  shifts: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.HR_MANAGER],
  users: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.HR_MANAGER],
  roles: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.HR_MANAGER],
  warehouses: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.WAREHOUSE_MANAGER, ROLES.DISPATCHER],
  warehouseLocations: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.WAREHOUSE_MANAGER, ROLES.DISPATCHER, ROLES.WORKER],
  products: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.WAREHOUSE_MANAGER, ROLES.DISPATCHER],
  inventory: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.WAREHOUSE_MANAGER, ROLES.DISPATCHER],
  stockMovements: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.WAREHOUSE_MANAGER, ROLES.DISPATCHER],
  stockMovementCreate: [ROLES.OVERLORD, ROLES.WAREHOUSE_MANAGER],
  transports: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.DISPATCHER, ROLES.WAREHOUSE_MANAGER, ROLES.DRIVER],
  vehicles: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.DISPATCHER],
  vehicleMaintenance: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.DISPATCHER],
  tasks: [
    ROLES.OVERLORD,
    ROLES.COMPANY_ADMIN,
    ROLES.HR_MANAGER,
    ROLES.WAREHOUSE_MANAGER,
    ROLES.DISPATCHER,
    ROLES.DRIVER,
    ROLES.WORKER,
  ],
  reports: [
    ROLES.OVERLORD,
    ROLES.COMPANY_ADMIN,
    ROLES.HR_MANAGER,
    ROLES.WAREHOUSE_MANAGER,
    ROLES.DISPATCHER,
  ],
  dataExchange: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.HR_MANAGER, ROLES.WAREHOUSE_MANAGER, ROLES.DISPATCHER],
  notifications: [
    ROLES.OVERLORD,
    ROLES.COMPANY_ADMIN,
    ROLES.HR_MANAGER,
    ROLES.WAREHOUSE_MANAGER,
    ROLES.DISPATCHER,
    ROLES.DRIVER,
    ROLES.WORKER,
  ],
  activityTimeline: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.WAREHOUSE_MANAGER, ROLES.DISPATCHER],
  changeHistory: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.HR_MANAGER, ROLES.WAREHOUSE_MANAGER, ROLES.DISPATCHER],
  audit: [ROLES.OVERLORD],
} as const;

export type ModuleKey = keyof typeof MODULE_ROLE_MATRIX;

export function canAccessModule(role: Role | undefined, module: ModuleKey): boolean {
  if (!role) {
    return false;
  }

  return MODULE_ROLE_MATRIX[module].includes(role);
}
