import { ROLES, type Role } from '../constants/roles';
import { CAPABILITIES, rolesForCapability } from './capabilities';

export const MODULE_ROLE_MATRIX: Record<string, readonly Role[]> = {
  dashboard: [
    ROLES.OVERLORD,
    ROLES.COMPANY_ADMIN,
    ROLES.HR_MANAGER,
    ROLES.WAREHOUSE_MANAGER,
    ROLES.DISPATCHER,
    ROLES.DRIVER,
    ROLES.WORKER,
  ],
  companies: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN],
  companyRequests: [ROLES.OVERLORD],
  employees: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.HR_MANAGER, ROLES.WAREHOUSE_MANAGER, ROLES.DISPATCHER],
  shifts: rolesForCapability(CAPABILITIES.SHIFT_READ_ALL),
  users: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.HR_MANAGER],
  roles: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.HR_MANAGER],
  warehouses: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.WAREHOUSE_MANAGER, ROLES.DISPATCHER, ROLES.DRIVER, ROLES.WORKER],
  warehouseLocations: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.WAREHOUSE_MANAGER, ROLES.DISPATCHER, ROLES.DRIVER, ROLES.WORKER],
  products: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.WAREHOUSE_MANAGER, ROLES.DISPATCHER, ROLES.DRIVER, ROLES.WORKER],
  inventory: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.WAREHOUSE_MANAGER, ROLES.DISPATCHER, ROLES.DRIVER, ROLES.WORKER],
  stockMovements: rolesForCapability(CAPABILITIES.STOCK_MOVEMENT_READ),
  stockMovementCreate: rolesForCapability(CAPABILITIES.STOCK_MOVEMENT_CREATE),
  transports: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.DISPATCHER, ROLES.WAREHOUSE_MANAGER, ROLES.DRIVER, ROLES.WORKER],
  vehicles: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.DISPATCHER, ROLES.DRIVER, ROLES.WORKER],
  vehicleMaintenance: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.DISPATCHER,
    ROLES.DRIVER, ROLES.WORKER],
  tasks: [
    ROLES.OVERLORD,
    ROLES.COMPANY_ADMIN,
    ROLES.HR_MANAGER,
    ROLES.WAREHOUSE_MANAGER,
    ROLES.DISPATCHER,
    ROLES.DRIVER,
    ROLES.WORKER,
  ],
  reports: [
    ROLES.OVERLORD,
    ROLES.COMPANY_ADMIN,
    ROLES.HR_MANAGER,
    ROLES.WAREHOUSE_MANAGER,
    ROLES.DISPATCHER,
  ],
  dataExchange: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.HR_MANAGER, ROLES.WAREHOUSE_MANAGER, ROLES.DISPATCHER],
  notifications: [
    ROLES.OVERLORD,
    ROLES.COMPANY_ADMIN,
    ROLES.HR_MANAGER,
    ROLES.WAREHOUSE_MANAGER,
    ROLES.DISPATCHER,
    ROLES.DRIVER,
    ROLES.WORKER,
  ],
  activityTimeline: [ROLES.OVERLORD],
  changeHistory: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN, ROLES.HR_MANAGER, ROLES.WAREHOUSE_MANAGER, ROLES.DISPATCHER],
  audit: [ROLES.OVERLORD, ROLES.COMPANY_ADMIN],
} as const;

export type ModuleKey = keyof typeof MODULE_ROLE_MATRIX;

export function canAccessModule(role: Role | undefined, module: ModuleKey): boolean {
  if (!role) {
    return false;
  }

  return MODULE_ROLE_MATRIX[module].includes(role);
}
