package rs.logistics.logistics_system.mapper;

import rs.logistics.logistics_system.dto.create.EmployeeCreate;
import rs.logistics.logistics_system.dto.response.EmployeeResponse;
import rs.logistics.logistics_system.dto.update.EmployeeUpdate;
import rs.logistics.logistics_system.entity.City;
import rs.logistics.logistics_system.entity.Country;
import rs.logistics.logistics_system.entity.Employee;
import rs.logistics.logistics_system.entity.Timezone;
import rs.logistics.logistics_system.entity.User;
import rs.logistics.logistics_system.entity.Warehouse;

import java.text.Normalizer;
import java.util.Locale;

public class EmployeeMapper {

    public static Employee toEntity(EmployeeCreate dto, User user, Timezone timezone) {
        Employee employee = new Employee(dto.getFirstName(), dto.getLastName(), dto.getJmbg(), dto.getPhoneNumber(), dto.getEmail(), dto.getPosition(), dto.getEmploymentDate(), dto.getSalary(), user);
        employee.setAddress(dto.getAddress());
        employee.setPostalCode(dto.getPostalCode());
        employee.setTimezone(timezone);
        return employee;
    }

    public static void updateEntity(EmployeeUpdate dto, Employee entity, User user, Timezone timezone) {
        entity.setFirstName(dto.getFirstName());
        entity.setLastName(dto.getLastName());
        entity.setJmbg(dto.getJmbg());
        entity.setPhoneNumber(dto.getPhoneNumber());
        entity.setEmail(dto.getEmail());
        entity.setAddress(dto.getAddress());
        entity.setPostalCode(dto.getPostalCode());
        entity.setTimezone(timezone);
        entity.setPosition(dto.getPosition());
        entity.setEmploymentDate(dto.getEmploymentDate());
        entity.setSalary(dto.getSalary());
        entity.setUser(user);
    }

    public static EmployeeResponse toResponse(Employee employee) {
        Country country = employee.getCountry();
        City city = employee.getCity();
        Timezone timezone = employee.getTimezone();
        Warehouse primaryWarehouse = employee.getPrimaryWarehouse();
        EmployeeResponse response = new EmployeeResponse();
        response.setId(employee.getId());
        response.setFirstName(employee.getFirstName());
        response.setLastName(employee.getLastName());
        response.setJmbg(employee.getJmbg());
        response.setPhoneCode(country != null ? country.getPhoneCode() : null);
        response.setPhoneNumber(employee.getPhoneNumber());
        response.setEmail(employee.getEmail());
        response.setAutoGeneratedEmail(employee.getAutoGeneratedEmail());
        response.setEmailManuallyOverridden(employee.getEmailManuallyOverridden());
        response.setEmailGenerationSource(employee.getEmailGenerationSource());
        String suggestedGeneratedEmail = buildSuggestedGeneratedEmail(employee);
        response.setSuggestedGeneratedEmail(suggestedGeneratedEmail);
        response.setGeneratedEmailOutdated(suggestedGeneratedEmail != null
                && employee.getEmail() != null
                && !suggestedGeneratedEmail.equalsIgnoreCase(employee.getEmail())
                && !Boolean.TRUE.equals(employee.getEmailManuallyOverridden()));
        response.setAddress(employee.getAddress());
        response.setCityId(city != null ? city.getId() : null);
        response.setCityName(city != null ? city.getName() : null);
        response.setCity(city != null ? city.getName() : null);
        response.setPostalCode(employee.getPostalCode());
        response.setTimezoneId(timezone != null ? timezone.getId() : null);
        response.setTimezoneName(timezone != null ? timezone.getName() : null);
        response.setTimezoneDisplayName(timezone != null ? timezone.getDisplayName() : null);
        response.setTimezone(timezone != null ? timezone.getName() : null);
        response.setCountryId(country != null ? country.getId() : null);
        response.setCountryCode(country != null ? country.getIso2Code() : null);
        response.setCountryName(country != null ? country.getName() : null);
        response.setPrimaryWarehouseId(primaryWarehouse != null ? primaryWarehouse.getId() : null);
        response.setPrimaryWarehouseName(primaryWarehouse != null ? primaryWarehouse.getName() : null);
        response.setPosition(employee.getPosition());
        response.setEmploymentDate(employee.getEmploymentDate());
        response.setSalary(employee.getSalary());
        response.setActive(employee.getActive());
        response.setUserId(employee.getUser() != null ? employee.getUser().getId() : null);
        response.setCompanyId(employee.getCompany() != null ? employee.getCompany().getId() : null);
        response.setCompanyName(employee.getCompany() != null ? employee.getCompany().getName() : null);
        return response;
    }

    private static String buildSuggestedGeneratedEmail(Employee employee) {
        if (employee == null || employee.getCompany() == null || employee.getCountry() == null || employee.getPosition() == null) {
            return null;
        }

        String localPart = (normalizeForEmailPart(employee.getFirstName(), false) + "." + normalizeForEmailPart(employee.getLastName(), false))
                .replaceAll("\\.+", ".")
                .replaceAll("^\\.|\\.$", "");
        String companySlug = normalizeForEmailPart(employee.getCompany().getName(), true);
        String positionSlug = normalizeForEmailPart(employee.getPosition().name(), true);
        String countrySlug = normalizeForEmailPart(employee.getCountry().getIso2Code(), true);

        if (localPart.isBlank() || companySlug.isBlank() || positionSlug.isBlank() || countrySlug.isBlank()) {
            return null;
        }

        return localPart + "@" + companySlug + "." + positionSlug + "." + countrySlug;
    }

    private static String normalizeForEmailPart(String value, boolean allowHyphen) {
        String normalized = Normalizer.normalize(value == null ? "" : value.trim(), Normalizer.Form.NFD)
                .replaceAll("\\p{M}", "")
                .replace("đ", "dj")
                .replace("Đ", "dj")
                .toLowerCase(Locale.ROOT);
        normalized = allowHyphen
                ? normalized.replaceAll("[^a-z0-9]+", "-")
                : normalized.replaceAll("[^a-z0-9]+", ".");
        normalized = normalized
                .replaceAll("[-.]{2,}", allowHyphen ? "-" : ".")
                .replaceAll("^[-.]+|[-.]+$", "");
        return normalized.length() > 40 ? normalized.substring(0, 40).replaceAll("[-.]+$", "") : normalized;
    }
}
