export const NOTIFICATION_POLL_INTERVAL_MS = 120_000;
export const NOTIFICATION_SSE_RECONNECT_MS = 5_000;
export const NOTIFICATION_SSE_MAX_RECONNECT_MS = 60_000;
export const NOTIFICATION_SSE_VISIBLE_REFRESH_DEBOUNCE_MS = 500;
export const NOTIFICATION_SSE_SEEN_EVENT_LIMIT = 100;
