spring.application.name=logistics-system

server.port=8080

#SQL server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Logistics;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=kosovosrbija
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#CleanerConsole
spring.main.banner-mode=off
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.com.zaxxer.hikari=WARN

#JWT service key
