spring.datasource.username=sa
spring.datasource.password=kosovosrbija

jwt.secret=${JWT_SECRET:bG9jYWwtZGV2LW9ubHktand0LXNlY3JldC0zMi1ieXRlcyEh}

spring.jpa.show-sql=true
logging.level.org.flywaydb=INFO
logging.level.org.springframework.boot.autoconfigure.flyway=INFO