export const ROLES = {
  OVERLORD: 'OVERLORD',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  HR_MANAGER: 'HR_MANAGER',
  WAREHOUSE_MANAGER: 'WAREHOUSE_MANAGER',
  DISPATCHER: 'DISPATCHER',
  DRIVER: 'DRIVER',
  WORKER: 'WORKER',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const ALL_ROLES = Object.values(ROLES) as Role[];

export const MANAGEMENT_ROLES: readonly Role[] = [
  ROLES.OVERLORD,
  ROLES.COMPANY_ADMIN,
  ROLES.HR_MANAGER,
  ROLES.WAREHOUSE_MANAGER,
  ROLES.DISPATCHER,
] as const;

export const COMPANY_SCOPED_ADMIN_ROLES: readonly Role[] = [
  ROLES.COMPANY_ADMIN,
  ROLES.HR_MANAGER,
  ROLES.WAREHOUSE_MANAGER,
  ROLES.DISPATCHER,
] as const;